version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: .
    binary: go-starter-utils
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X '{{ .ModulePath }}/cmd.Version={{ .Version }}'
      - -X '{{ .ModulePath }}/cmd.Commit={{ .ShortCommit }}'
      - -X '{{ .ModulePath }}/cmd.Date={{ .Date }}'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
